### ISSUE TITLE
Parsing devices fails on Xcode 15.3

### ISSUE THREAD

**Issue by aegzorz** [brightdigit/SimulatorServices#14]
When parsing the device list the parsing fails because the `dataPathSize` field seems to be missing when running a simulator from Xcode 15.3.

**Comment by leogdion** [comment]
Awesome! Thanks @aegzorz 
I'm going to tag it later this week.

**Comment by aegzorz** [comment]
> Awesome! Thanks @aegzorz I'm going to tag it later this week.

Nice! 🙌

**Comment by leogdion** [comment]
This has been included in #16 use tag 1.1.0-beta.2 to try it out
